from dotenv import load_dotenv
from os import environ
from datetime import timedelta

load_dotenv()

class Config:
  SECRET_KEY = environ['SECRET_KEY']
  SQLALCHEMY_DATABASE_URI = environ['DATABASE_URL']
  SQLALCHEMY_TRACK_MODIFICATIONS = False
  SQLALCHEMY_ENGINE_OPTIONS = {
    "pool_pre_ping": True,
  }
  PRESERVE_CONTEXT_ON_EXCEPTION = False
  SESSION_COOKIE_SECURE=True
  SESSION_COOKIE_HTTPONLY=True
  REMEMBER_COOKIE_DURATION = timedelta(days=30)
  SESSION_COOKIE_SAMESITE = 'Lax'
  REMEMBER_COOKIE_SAMESITE = 'strict'
  SECURITY_PASSWORD_SALT = environ['SALT']
  APP_VERSION = "Alpha 0.1.0"
  APP_NAME = "FlaskApp"
  FA = environ['FA']
  TYPEKIT = environ['TYPEKIT']
  MAIL_SERVER = "smtp.gmail.com"
  MAIL_PORT = 465
  MAIL_USE_SSL = True
  MAIL_USERNAME = environ['EMAIL_USERNAME']
  MAIL_PASSWORD = environ['EMAIL_PASSWORD']
  MAIL_DEFAULT_SENDER = environ['EMAIL_ALIAS']
  API_TITLE = "API"
  API_VERSION = "v1"
  OPENAPI_VERSION = "3.1.1"
  DEBUG_TB_INTERCEPT_REDIRECTS = False
  TURNSTILE_SECRET_KEY = environ['TURNSTILE_SECRET_KEY']
  TURNSTILE_SITE_KEY = environ['TURNSTILE_SITE_KEY']
  GOOGLE_CLIENT_ID = environ['GOOGLE_CLIENT_ID']
  GOOGLE_CLIENT_SECRET = environ['GOOGLE_CLIENT_SECRET']